openapi: 3.0.1
info:
  title: 3d store-trigger
  description: Ingesting and exporting 3d model to S3/NFS
  version: 1.5.1
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
paths:
  /jobStatus/{jobId}:
    get:
      operationId: getJobStatus
      tags:
        - jobStatus
      summary: gets the resource
      parameters:
        - $ref: '#/components/parameters/jobId'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobStatus'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /ingestion:
    post:
      operationId: createModel
      tags:
        - ingestion
      summary: creates a new job and invokes a new model ingestion flow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payload'
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '500':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  parameters:
    jobId:
      in: path
      name: jobId
      required: true
      schema:
        type: string
      description: The jobId for status check
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    payload:
      type: object
      description: 3d model payload
      required:
        - modelId
        - pathToTileset
        - tilesetFilename
        - metadata
      properties:
        modelId:
          type: string
          description: Model identifier
          example: a2234fdf
        pathToTileset:
          type: string
          description: path to tileset
          example: NewYork
        tilesetFilename:
          type: string
          description: Model tileset filename
          example: tileset.json
        metadata:
          $ref: >-
            ./Schema/3dCatalog/3dMetadata.yaml#/components/schemas/ingestion-payload
      additionalProperties: false
    createResponse:
      type: object
      description: The ingestion response
      required:
        - jobId
        - status
      properties:
        status:
          type: string
          enum:
            - Completed
            - In-Progress
            - Pending
            - Failed
            - Expired
            - Aborted
        jobId:
          type: string
          description: job id
    jobStatus:
      type: object
      description: The job response
      required:
        - status
        - percentage
      properties:
        percentage:
          type: number
          minimum: 0
          maximum: 100
          description: percentage of task by job id
        status:
          type: string
          enum:
            - Completed
            - In-Progress
            - Pending
            - Failed
            - Expired
            - Aborted
