openapi: 3.0.1
info:
  title: 3d exporter trigger
  description: Exporting 3d model to S3/NFS
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /jobStatus/{jobID}:
    get:
      operationId: getJobStatus
      tags:
        - jobStatus
      summary: gets the resource
      parameters:
        - $ref: '#/components/parameters/jobID'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/jobStatus'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

  /export:
    post:
      operationId: createModel
      tags:
        - export
      summary: creates a new job and invokes a new model exporter flow
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/payload'
      responses:
        201:
          description: created
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/job'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
        '5XX':
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  parameters:
    jobID:
      in: path
      name: jobID
      required: true
      schema:
        type: string
      description: The jobID for status check
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    payload:
      type: object
      description: 3d model payload
      required:
        - modelId
        - modelPath
        - tilesetFileName
        - metadata
      properties:
        modelId:
          type: string
          description: Model identifier
          example: 'a2234fdf'
        modelPath:
          type: string
          description: Model files location path
          example: '//domtest/mimi/archi/maz/silver/libot/NewYork'
        tilesetFileName:
          type: string
          description: Model tileset filename
          example: 'tileset.json'
        metadata:
          $ref: './Schema/3dCatalog/3dMetadata.yaml#/components/schemas/payload'
      additionalProperties: false
    jobStatus:
      type: object
      description: The job response
      required:
        - status
        - percentage
      properties:
        percentage:
          type: number
          minimum: 0
          maximum: 100
          description: percentage of task by job id
        status:
          type: string
          enum:
            - Completed
            - In-Progress
            - Pending
            - Failed
            - Expired
            - Aborted
          